-- ============================================================================
-- AMALGAMA — Complete PostgreSQL schema for VPS (api.serointeam.ru)
-- ----------------------------------------------------------------------------
-- This migration adds ALL game tables missing from the original vps_schema.sql.
-- It is safe to run on an existing database: uses CREATE TABLE IF NOT EXISTS,
-- CREATE INDEX IF NOT EXISTS, and DO $$ blocks for ALTER TABLE additions.
--
-- No DROP TABLE. No data deletion. No recreation of existing tables.
--
-- HOW TO APPLY:
--   psql -U seroin_user -d seroin_app -f vps_schema_latest.sql
--
-- Or paste into pgAdmin / Adminer / DBeaver.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================================
-- BASE TABLES (from original vps_schema.sql — already exist, IF NOT EXISTS is safe)
-- ============================================================================

CREATE TABLE IF NOT EXISTS employees (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name   text        NOT NULL,
  organization text       NOT NULL,
  access_date date        NOT NULL,
  record_type text        NOT NULL DEFAULT 'person',
  vehicle_type text,
  created_at  timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS memes (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  description text        NOT NULL,
  image_url   text,
  created_at  timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS game_workers (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name       text        NOT NULL UNIQUE CHECK (length(trim(name)) BETWEEN 2 AND 120),
  gender     text        NOT NULL CHECK (gender IN ('м', 'ж')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS team_stats (
  worker_name text        PRIMARY KEY REFERENCES game_workers(name) ON DELETE CASCADE,
  weight      int         NOT NULL DEFAULT 0,
  happiness   int         NOT NULL DEFAULT 0,
  balance     int         NOT NULL DEFAULT 0,
  title_level int         NOT NULL DEFAULT 1,
  title_xp    int         NOT NULL DEFAULT 0,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS prediction_counts (
  name       text        PRIMARY KEY,
  count      int         NOT NULL DEFAULT 0 CHECK (count >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS secret_attempts (
  id         int         PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  attempts   int         NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO secret_attempts (id, attempts) VALUES (1, 0)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS import_log (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  source_key  text        UNIQUE NOT NULL,
  row_count   int         NOT NULL,
  imported_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    text        NOT NULL,
  nickname   text        NOT NULL,
  message    text        NOT NULL CHECK (char_length(message) > 0 AND char_length(message) <= 300),
  chat_day   date        NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_day_created
  ON chat_messages (chat_day, created_at);

CREATE TABLE IF NOT EXISTS chat_nicks (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    text        NOT NULL,
  nickname   text        NOT NULL,
  chat_day   date        NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chat_nicks_nick_day_unique UNIQUE (nickname, chat_day),
  CONSTRAINT chat_nicks_user_day_unique UNIQUE (user_id, chat_day)
);

CREATE INDEX IF NOT EXISTS idx_chat_nicks_day
  ON chat_nicks (chat_day);

CREATE TABLE IF NOT EXISTS team_daily_votes (
  id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_day   date        NOT NULL,
  voter_name text        NOT NULL,
  question   text        NOT NULL,
  choice_1   text        NOT NULL,
  choice_2   text        NOT NULL,
  choice_3   text        NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (game_day, voter_name)
);

CREATE TABLE IF NOT EXISTS test_questions (
  question_id    text        PRIMARY KEY,
  question_text  text        NOT NULL,
  options        jsonb       NOT NULL DEFAULT '[]'::jsonb,
  correct_answer int         CHECK (correct_answer IS NULL OR correct_answer >= 0),
  created_at     timestamptz DEFAULT now(),
  updated_at     timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_test_questions_correct
  ON test_questions (correct_answer);

-- ============================================================================
-- PLAYERS — alias view for game_workers (some backend code references "players")
-- ============================================================================
-- If the backend queries "SELECT * FROM players", this view provides compatibility.
CREATE OR REPLACE VIEW players AS
  SELECT name AS player_name, name, gender, created_at
  FROM game_workers;

-- ============================================================================
-- MINI GAME PROFILE & PROGRESS
-- ============================================================================

CREATE TABLE IF NOT EXISTS mini_game_profile (
  user_id     text        PRIMARY KEY,
  level       int         NOT NULL DEFAULT 1,
  xp          int         NOT NULL DEFAULT 0,
  coins       int         NOT NULL DEFAULT 0,
  title       text        NOT NULL DEFAULT 'Новичок',
  title_xp    int         NOT NULL DEFAULT 0,
  title_level int         NOT NULL DEFAULT 1,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mini_game_progress (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     text        NOT NULL,
  game_number int         NOT NULL CHECK (game_number >= 1 AND game_number <= 10),
  completed   boolean     NOT NULL DEFAULT false,
  best_score  int         NOT NULL DEFAULT 0,
  played_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, game_number)
);

-- ============================================================================
-- ECONOMY — transaction audit logs
-- ============================================================================

CREATE TABLE IF NOT EXISTS xp_transactions (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     text        NOT NULL,
  amount      int         NOT NULL,
  reason      text        NOT NULL,
  game_key    text,
  game_day    date,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS coin_transactions (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     text        NOT NULL,
  amount      int         NOT NULL,
  reason      text        NOT NULL,
  game_key    text,
  game_day    date,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- DAILY GAME COMPLETIONS & SET REWARDS
-- ============================================================================

CREATE TABLE IF NOT EXISTS daily_game_completions (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     text        NOT NULL,
  game_key    text        NOT NULL,
  game_day    date        NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, game_key, game_day)
);

CREATE TABLE IF NOT EXISTS daily_game_set_rewards (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         text        NOT NULL,
  game_day        date        NOT NULL,
  bonus_rewarded  boolean     NOT NULL DEFAULT false,
  title_xp_awarded int        NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, game_day)
);

-- ============================================================================
-- GAME #1: DAILY POLL ("Вопрос дня")
-- ============================================================================

CREATE TABLE IF NOT EXISTS daily_poll_questions (
  id          serial      PRIMARY KEY,
  question    text        NOT NULL,
  active      boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS daily_polls (
  id          serial      PRIMARY KEY,
  question_id int         NOT NULL REFERENCES daily_poll_questions(id) ON DELETE CASCADE,
  poll_date   date        NOT NULL UNIQUE,
  candidate_1 text        NOT NULL,
  candidate_2 text        NOT NULL,
  candidate_3 text        NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS daily_poll_user_votes (
  id                uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  daily_poll_id     int         NOT NULL REFERENCES daily_polls(id) ON DELETE CASCADE,
  user_id           text        NOT NULL,
  selected_candidates text[]   NOT NULL,
  voted_at          timestamptz NOT NULL DEFAULT now(),
  UNIQUE (daily_poll_id, user_id)
);

CREATE TABLE IF NOT EXISTS daily_poll_rewards (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  daily_poll_id       int         NOT NULL REFERENCES daily_polls(id) ON DELETE CASCADE,
  user_id             text        NOT NULL,
  participation_rewarded boolean NOT NULL DEFAULT false,
  result_rewarded     boolean     NOT NULL DEFAULT false,
  xp_awarded          int         NOT NULL DEFAULT 0,
  title_xp_awarded    int         NOT NULL DEFAULT 0,
  created_at          timestamptz NOT NULL DEFAULT now(),
  UNIQUE (daily_poll_id, user_id)
);

-- ============================================================================
-- GAME #2: WHO OF THEM ("Кто из них?")
-- ============================================================================

CREATE TABLE IF NOT EXISTS who_of_them_daily (
  id              serial      PRIMARY KEY,
  game_day        date        NOT NULL UNIQUE,
  question_index  int         NOT NULL DEFAULT 0,
  player_1        text        NOT NULL,
  player_2        text        NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS who_of_them_votes (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day        date        NOT NULL,
  user_id         text        NOT NULL,
  selected_player text        NOT NULL,
  voted_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (game_day, user_id)
);

CREATE TABLE IF NOT EXISTS who_of_them_rewards (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day                date        NOT NULL,
  user_id                 text        NOT NULL,
  participation_rewarded  boolean     NOT NULL DEFAULT false,
  result_rewarded         boolean     NOT NULL DEFAULT false,
  xp_awarded              int         NOT NULL DEFAULT 0,
  title_xp_awarded        int         NOT NULL DEFAULT 0,
  coins_awarded           int         NOT NULL DEFAULT 0,
  UNIQUE (game_day, user_id)
);

-- ============================================================================
-- GAME #3: WOULD HE DO IT ("Сделал бы за 100 000?")
-- ============================================================================

CREATE TABLE IF NOT EXISTS would_he_do_it_daily (
  id              serial      PRIMARY KEY,
  game_day        date        NOT NULL UNIQUE,
  question_index  int         NOT NULL DEFAULT 0,
  player_name     text        NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS would_he_do_it_votes (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day        date        NOT NULL,
  user_id         text        NOT NULL,
  vote            text        NOT NULL CHECK (vote IN ('yes', 'no')),
  voted_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (game_day, user_id)
);

CREATE TABLE IF NOT EXISTS would_he_do_it_rewards (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day                date        NOT NULL,
  user_id                 text        NOT NULL,
  participation_rewarded  boolean     NOT NULL DEFAULT false,
  result_rewarded         boolean     NOT NULL DEFAULT false,
  xp_awarded              int         NOT NULL DEFAULT 0,
  title_xp_awarded        int         NOT NULL DEFAULT 0,
  coins_awarded           int         NOT NULL DEFAULT 0,
  UNIQUE (game_day, user_id)
);

-- ============================================================================
-- GAME #4: PAST LIFE ("Прошлая жизнь")
-- ============================================================================

CREATE TABLE IF NOT EXISTS past_life_daily (
  id              serial      PRIMARY KEY,
  game_day        date        NOT NULL UNIQUE,
  question_index  int         NOT NULL DEFAULT 0,
  player_1        text        NOT NULL,
  player_2        text        NOT NULL,
  player_3        text        NOT NULL,
  correct_index   int         NOT NULL CHECK (correct_index >= 0 AND correct_index <= 2),
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS past_life_votes (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day        date        NOT NULL,
  user_id         text        NOT NULL,
  selected_index  int         NOT NULL CHECK (selected_index >= 0 AND selected_index <= 2),
  is_correct      boolean     NOT NULL,
  voted_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (game_day, user_id)
);

CREATE TABLE IF NOT EXISTS past_life_rewards (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day                date        NOT NULL,
  user_id                 text        NOT NULL,
  participation_rewarded  boolean     NOT NULL DEFAULT false,
  result_rewarded         boolean     NOT NULL DEFAULT false,
  xp_awarded              int         NOT NULL DEFAULT 0,
  title_xp_awarded        int         NOT NULL DEFAULT 0,
  coins_awarded           int         NOT NULL DEFAULT 0,
  UNIQUE (game_day, user_id)
);

-- ============================================================================
-- GAME #5: BEST DUO ("Какой дуэт лучше?")
-- ============================================================================

CREATE TABLE IF NOT EXISTS best_duo_daily (
  id              serial      PRIMARY KEY,
  game_day        date        NOT NULL UNIQUE,
  question_index  int         NOT NULL DEFAULT 0,
  player_1        text        NOT NULL,
  player_2        text        NOT NULL,
  player_3        text        NOT NULL,
  player_4        text        NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS best_duo_votes (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day        date        NOT NULL,
  user_id         text        NOT NULL,
  selected_team   int         NOT NULL CHECK (selected_team IN (1, 2)),
  voted_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (game_day, user_id)
);

CREATE TABLE IF NOT EXISTS best_duo_rewards (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day                date        NOT NULL,
  user_id                 text        NOT NULL,
  participation_rewarded  boolean     NOT NULL DEFAULT false,
  result_rewarded         boolean     NOT NULL DEFAULT false,
  xp_awarded              int         NOT NULL DEFAULT 0,
  title_xp_awarded        int         NOT NULL DEFAULT 0,
  coins_awarded           int         NOT NULL DEFAULT 0,
  UNIQUE (game_day, user_id)
);

-- ============================================================================
-- GAME #6: RATE PLAYER ("Оцени")
-- ============================================================================

CREATE TABLE IF NOT EXISTS rate_player_daily (
  id              serial      PRIMARY KEY,
  game_day        date        NOT NULL UNIQUE,
  question_index  int         NOT NULL DEFAULT 0,
  player_name     text        NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rate_player_votes (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day        date        NOT NULL,
  user_id         text        NOT NULL,
  rating          int         NOT NULL CHECK (rating >= 0 AND rating <= 5),
  voted_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (game_day, user_id)
);

CREATE TABLE IF NOT EXISTS rate_player_rewards (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day                date        NOT NULL,
  user_id                 text        NOT NULL,
  participation_rewarded  boolean     NOT NULL DEFAULT false,
  result_rewarded         boolean     NOT NULL DEFAULT false,
  xp_awarded              int         NOT NULL DEFAULT 0,
  title_xp_awarded        int         NOT NULL DEFAULT 0,
  coins_awarded           int         NOT NULL DEFAULT 0,
  UNIQUE (game_day, user_id)
);

-- ============================================================================
-- GAME #7: MAFIA ("Угадай мафию")
-- ============================================================================

CREATE TABLE IF NOT EXISTS mafia_daily (
  id              serial      PRIMARY KEY,
  game_day        date        NOT NULL UNIQUE,
  question_index  int         NOT NULL DEFAULT 0,
  player_1        text        NOT NULL,
  player_2        text        NOT NULL,
  player_3        text        NOT NULL,
  player_4        text        NOT NULL,
  player_5        text        NOT NULL,
  mafia_index     int         NOT NULL CHECK (mafia_index >= 0 AND mafia_index <= 4),
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mafia_user_state (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day        date        NOT NULL,
  user_id         text        NOT NULL,
  attempt_count   int         NOT NULL DEFAULT 0,
  eliminated_1    int,
  eliminated_2    int,
  found_mafia     boolean     NOT NULL DEFAULT false,
  game_ended      boolean     NOT NULL DEFAULT false,
  updated_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (game_day, user_id)
);

CREATE TABLE IF NOT EXISTS mafia_rewards (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day                date        NOT NULL,
  user_id                 text        NOT NULL,
  participation_rewarded  boolean     NOT NULL DEFAULT false,
  result_rewarded         boolean     NOT NULL DEFAULT false,
  xp_awarded              int         NOT NULL DEFAULT 0,
  title_xp_awarded        int         NOT NULL DEFAULT 0,
  coins_awarded           int         NOT NULL DEFAULT 0,
  UNIQUE (game_day, user_id)
);

CREATE TABLE IF NOT EXISTS mafia_attempts (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day        date        NOT NULL,
  user_id         text        NOT NULL,
  attempt_number  int         NOT NULL,
  selected_index  int         NOT NULL,
  is_mafia        boolean     NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- GAME #8: YES/NO ("Да или Нет")
-- ============================================================================

CREATE TABLE IF NOT EXISTS yes_no_daily (
  id              serial      PRIMARY KEY,
  game_day        date        NOT NULL UNIQUE,
  question_index  int         NOT NULL DEFAULT 0,
  player_name     text        NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS yes_no_votes (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day        date        NOT NULL,
  user_id         text        NOT NULL,
  vote            text        NOT NULL CHECK (vote IN ('yes', 'no')),
  voted_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (game_day, user_id)
);

CREATE TABLE IF NOT EXISTS yes_no_rewards (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day                date        NOT NULL,
  user_id                 text        NOT NULL,
  participation_rewarded  boolean     NOT NULL DEFAULT false,
  result_rewarded         boolean     NOT NULL DEFAULT false,
  xp_awarded              int         NOT NULL DEFAULT 0,
  title_xp_awarded        int         NOT NULL DEFAULT 0,
  coins_awarded           int         NOT NULL DEFAULT 0,
  UNIQUE (game_day, user_id)
);

-- ============================================================================
-- GAME #9: SECRET LOVE ("Тайная любовь")
-- ============================================================================

CREATE TABLE IF NOT EXISTS secret_love_user_daily (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day        date        NOT NULL,
  user_id         text        NOT NULL,
  player_1        text        NOT NULL,
  player_2        text        NOT NULL,
  player_3        text        NOT NULL,
  correct_index   int         NOT NULL CHECK (correct_index >= 0 AND correct_index <= 2),
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (game_day, user_id)
);

CREATE TABLE IF NOT EXISTS secret_love_user_state (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day        date        NOT NULL,
  user_id         text        NOT NULL,
  selected_index  int         NOT NULL CHECK (selected_index >= 0 AND selected_index <= 2),
  is_correct      boolean     NOT NULL,
  answered_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (game_day, user_id)
);

CREATE TABLE IF NOT EXISTS secret_love_rewards (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day                date        NOT NULL,
  user_id                 text        NOT NULL,
  participation_rewarded  boolean     NOT NULL DEFAULT false,
  result_rewarded         boolean     NOT NULL DEFAULT false,
  xp_awarded              int         NOT NULL DEFAULT 0,
  title_xp_awarded        int         NOT NULL DEFAULT 0,
  coins_awarded           int         NOT NULL DEFAULT 0,
  UNIQUE (game_day, user_id)
);

-- ============================================================================
-- GAME #10: ROULETTE ("Рулетка")
-- ============================================================================

CREATE TABLE IF NOT EXISTS roulette_user_daily (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day        date        NOT NULL,
  user_id         text        NOT NULL,
  opponent_name   text        NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (game_day, user_id)
);

CREATE TABLE IF NOT EXISTS roulette_user_state (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day        date        NOT NULL,
  user_id         text        NOT NULL,
  result          text        NOT NULL CHECK (result IN ('win', 'lose')),
  played_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (game_day, user_id)
);

CREATE TABLE IF NOT EXISTS roulette_rewards (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_day                date        NOT NULL,
  user_id                 text        NOT NULL,
  participation_rewarded  boolean     NOT NULL DEFAULT false,
  result_rewarded         boolean     NOT NULL DEFAULT false,
  xp_awarded              int         NOT NULL DEFAULT 0,
  title_xp_awarded        int         NOT NULL DEFAULT 0,
  coins_awarded           int         NOT NULL DEFAULT 0,
  UNIQUE (game_day, user_id)
);

-- ============================================================================
-- KNOWLEDGE NUMBERS ("Числа")
-- ============================================================================

CREATE TABLE IF NOT EXISTS knowledge_numbers (
  id          serial      PRIMARY KEY,
  number      int         NOT NULL UNIQUE,
  content     text        NOT NULL DEFAULT '',
  updated_at  timestamptz NOT NULL DEFAULT now()
);

INSERT INTO knowledge_numbers (number, content)
SELECT i, ''
FROM generate_series(1, 31) AS i
WHERE NOT EXISTS (SELECT 1 FROM knowledge_numbers kn WHERE kn.number = i);

-- ============================================================================
-- TEST QUESTION BLOCKS
-- ============================================================================

CREATE TABLE IF NOT EXISTS test_question_blocks (
  question_id  text        PRIMARY KEY,
  block_number int         NOT NULL CHECK (block_number >= 1 AND block_number <= 4),
  updated_at   timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_test_blocks_block_number
  ON test_question_blocks (block_number);

-- ============================================================================
-- INDEXES for game tables
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_xp_transactions_user ON xp_transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_coin_transactions_user ON coin_transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_daily_game_completions_user_day ON daily_game_completions (user_id, game_day);
CREATE INDEX IF NOT EXISTS idx_daily_game_set_rewards_user_day ON daily_game_set_rewards (user_id, game_day);

CREATE INDEX IF NOT EXISTS idx_who_of_them_votes_user ON who_of_them_votes (user_id);
CREATE INDEX IF NOT EXISTS idx_who_of_them_rewards_user ON who_of_them_rewards (user_id);

CREATE INDEX IF NOT EXISTS idx_would_he_do_it_votes_user ON would_he_do_it_votes (user_id);
CREATE INDEX IF NOT EXISTS idx_would_he_do_it_rewards_user ON would_he_do_it_rewards (user_id);

CREATE INDEX IF NOT EXISTS idx_past_life_votes_user ON past_life_votes (user_id);
CREATE INDEX IF NOT EXISTS idx_past_life_rewards_user ON past_life_rewards (user_id);

CREATE INDEX IF NOT EXISTS idx_best_duo_votes_user ON best_duo_votes (user_id);
CREATE INDEX IF NOT EXISTS idx_best_duo_rewards_user ON best_duo_rewards (user_id);

CREATE INDEX IF NOT EXISTS idx_rate_player_votes_user ON rate_player_votes (user_id);
CREATE INDEX IF NOT EXISTS idx_rate_player_rewards_user ON rate_player_rewards (user_id);

CREATE INDEX IF NOT EXISTS idx_mafia_user_state_user ON mafia_user_state (user_id);
CREATE INDEX IF NOT EXISTS idx_mafia_rewards_user ON mafia_rewards (user_id);
CREATE INDEX IF NOT EXISTS idx_mafia_attempts_user ON mafia_attempts (user_id);

CREATE INDEX IF NOT EXISTS idx_yes_no_votes_user ON yes_no_votes (user_id);
CREATE INDEX IF NOT EXISTS idx_yes_no_rewards_user ON yes_no_rewards (user_id);

CREATE INDEX IF NOT EXISTS idx_secret_love_user_daily_user ON secret_love_user_daily (user_id);
CREATE INDEX IF NOT EXISTS idx_secret_love_user_state_user ON secret_love_user_state (user_id);
CREATE INDEX IF NOT EXISTS idx_secret_love_rewards_user ON secret_love_rewards (user_id);

CREATE INDEX IF NOT EXISTS idx_roulette_user_daily_user ON roulette_user_daily (user_id);
CREATE INDEX IF NOT EXISTS idx_roulette_user_state_user ON roulette_user_state (user_id);
CREATE INDEX IF NOT EXISTS idx_roulette_rewards_user ON roulette_rewards (user_id);

CREATE INDEX IF NOT EXISTS idx_daily_poll_user_votes_user ON daily_poll_user_votes (user_id);
CREATE INDEX IF NOT EXISTS idx_daily_poll_rewards_user ON daily_poll_rewards (user_id);

CREATE INDEX IF NOT EXISTS idx_mini_game_progress_user ON mini_game_progress (user_id);

-- ============================================================================
-- END OF SCHEMA
-- ============================================================================
