create table if not exists team_daily_votes (
  id bigint generated by default as identity primary key,
  game_day date not null,
  voter_name text not null,
  question text not null,
  choice_1 text not null,
  choice_2 text not null,
  choice_3 text not null,
  created_at timestamptz not null default now(),

  unique (game_day, voter_name)
);

alter table team_daily_votes enable row level security;

create policy "team_daily_votes_select"
on team_daily_votes
for select
using (true);

create policy "team_daily_votes_insert"
on team_daily_votes
for insert
with check (true);